### ISSUE TITLE
rpy2 error with stream_atac.preprocess_atac() 

### ISSUE THREAD

**Issue by jingyaq** [pinellolab/STREAM#39] opened 2019-11-13 21:20 UTC
Hi,

Thank you for this tool! I think I successfully installed stream and stream_atac with anaconda3 in its own environment, but running into problems with stream_atac.preprocess_atac(). It gives me this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/stream_atac/core.py", line 142, in preprocess_atac
    r_regions_dataframe = pandas2ri.py2ri(df_regions)
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'

Do you know what the issue might be? My rpy2 version is 3.1.0 and pandas version is 0.25.3. Thanks so much!

**Comment by huidongchen** [comment] 2019-11-15 22:47
Hi, 

Thanks for the feedback. In rpy2 3.X they changed the way of converting dataframe (But in bioconda channel, only rpy2 2.X is available). Can you downgrade rpy2 3.X to rpy2 2.X and try it again?

**Comment by jingyaq** [comment] 2019-11-17 15:47
I tried downgrading to rpy2 2.8.6, and got a different error (see below). Do I need a specific version of the GenomicRanges R package? Thank you for your help!
______________________________________________

Read in files ...
/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]) : 
  some values in the "start" column cannot be turned into numeric values

  warnings.warn(x, RRuntimeWarning)
/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: In addition: 
  warnings.warn(x, RRuntimeWarning)
/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: There were 25 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/stream_atac/core.py", line 143, in preprocess_atac
    regions = GenomicRanges.makeGRangesFromDataFrame(r_regions_dataframe)
  File "/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/home/jingyaq/anaconda3-new/envs/STREAM/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]) : 
  some values in the "start" column cannot be turned into numeric values

**Comment by huidongchen** [comment] 2019-11-18 22:03
Instead of downgrading `rpy2` after creating your env, can you try to specify the rpy2 version while creating your env, something like

`conda create -n my_new_env python stream stream_atac rpy2=2.9 jupyter -y`

This should work.

**Comment by jingyaq** [comment] 2019-11-20 02:05
Still the same error when creating a new environment with specified rpy2 version 2.9.4 :(

**Comment by huidongchen** [comment] 2019-11-20 02:11
Sorry about the error. It was indeed an error caused by the new version of GenomicRanges package. I was able to reproduce it and am working on updating steam_atac. Hopefully it will be available in the next one or two days.

**Comment by huidongchen** [comment] 2019-11-24 20:58
The issue has been fixed in the latest `stream_atac 0.3.5`. Please check out the updated tutorial for single cell ATAC-seq preprocessing part https://github.com/pinellolab/STREAM_atac#tutorial

**Closed by huidongchen** 2019-11-24 20:58 UTC
