### ISSUE TITLE
Stream Installation, it hangs in solving environment 

### ISSUE THREAD

**Issue by linwang6** [pinellolab/STREAM#77] opened 2020-06-11 01:02 UTC
Hi, 
Thanks for this cool tool.
When I tried to install stream,

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create -n env_stream python stream jupyter
Solving environment: / 

it hangs in solving environment step, how to fix this? Any advice? 

Thanks in advance.

**Comment by huidongchen** [comment] 2020-06-11 01:33
Yeah, conda install usually does take some time. But just in case it gets stuck, can you specify stream version and give it try again? something like `conda create -n env_stream python stream=1.0 jupyter`?

**Comment by linwang6** [comment] 2020-06-11 01:38
Thanks huidong, I will have a try.

**Comment by linwang6** [comment] 2020-06-11 03:19
Hi huidong,
When I tried "conda create -n stream python stream=1.0 jupyter", it solved the solving environment step, but it gave a new error information, see below,
...............
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'conda-forge::attrs-19.3.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/Users/lwang/miniconda3/envs/SCstream/bin/python3.7'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/Users/lwang/miniconda3/envs/SCstream/bin/python3.7'")


Any suggestions? Thanks in advance.

**Comment by lucapinello** [comment] 2020-06-11 12:46
It seems a more general problem with conda and not STREAM, see here:
https://github.com/conda/conda/issues/8051

Which version of conda are you using? and are you on Mac?

You could try:

conda create -n stream-env python=3.7
conda activate stream-env
conda install stream=1.0 jupyter

Please keep us posted.

**Comment by linwang6** [comment] 2020-06-11 15:16
Thanks Luca, I'm using conda 4.4.10. Right, I'm on Mac. I will try this and update you.

**Comment by linwang6** [comment] 2020-06-11 16:03
Hi Luca, 
It works using your suggested command lines, and it's installed without any error. But when I import stream, it gives me segmentation fault 11, see below,

(stream) wanglin@Wangs-Mac:/Users/wanglin$ python

Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stream as st
cannot find system Renviron
/Users/wanglin/miniconda3/envs/stream/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Fatal error: unable to open the base package

  warnings.warn(x, RRuntimeWarning)
Segmentation fault: 11

That means it not find Renviron, how should I set it?  Thanks in advance.

**Comment by linwang6** [comment] 2020-06-11 16:14
Here is the R path
$ which R
/Users/wanglin/miniconda3/envs/stream/bin/R

**Comment by lucapinello** [comment] 2020-06-11 17:06
This is probably still a bug of the old conda version. Try to update to the
latest version i.e. 4.8 and potentially consider reinstalling miniconda
from scratch.

**Comment by linwang6** [comment] 2020-06-11 17:29
Got it, I will update conda, and try again. Thanks!

**Comment by linwang6** [comment] 2020-06-11 18:17
I have reinstalling the latest miniconda (https://docs.conda.io/en/latest/miniconda.html), and it still gives the same error,

(stream_env) wanglin@Wangs-MacBook-Pro-2:/Users/wanglin0$ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:33:30) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stream as st
cannot find system Renviron
/Users/wanglin/miniconda3/envs/stream_env/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Fatal error: unable to open the base package


  warnings.warn(x, RRuntimeWarning)
Segmentation fault: 11

Any advices? Thanks so much.

**Comment by huidongchen** [comment] 2020-06-11 18:23
It seems that someone has reported a similar issue previously #24 , but unfortunately I have not been able to reproduce this error myself. Can you share with us your pkg version info, i.e. the output from `conda list`?

**Comment by linwang6** [comment] 2020-06-11 18:27
Sure, see below,

(stream_env) wanglin@Wangs-MacBook-Pro-2:/Users/wanglin0$ conda list
# packages in environment at /Users/wanglin/miniconda3/envs/stream_env:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
anndata                   0.7.3            py37hc8dfbb8_0    conda-forge
appnope                   0.1.0           py37hc8dfbb8_1001    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
cctools                   927.0.2              h5ba7a2e_4    conda-forge
certifi                   2020.4.5.2       py37hc8dfbb8_0    conda-forge
clang                     9.0.1           default_hf57f61e_0    conda-forge
clang-tools               9.0.1           default_hf57f61e_0    conda-forge
clang_osx-64              9.0.1                h05bbb7f_0    conda-forge
clangxx                   9.0.1           default_hf57f61e_0    conda-forge
clangxx_osx-64            9.0.1                h05bbb7f_2    conda-forge
compiler-rt               9.0.1                h6a512c6_3    conda-forge
compiler-rt_osx-64        9.0.1                h99342c6_3    conda-forge
curl                      7.69.1               h2d98d24_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
fribidi                   1.0.9                h0b31af3_0    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gfortran_impl_osx-64      7.3.0                hf4212f2_2    conda-forge
gfortran_osx-64           7.3.0               h22b1bf0_11    conda-forge
glib                      2.64.3               h577aef8_0    conda-forge
gmp                       6.2.0                h4a8c4bd_2    conda-forge
graphite2                 1.3.13            h12caacf_1001    conda-forge
gsl                       2.6                  ha2d443c_0    conda-forge
gunicorn                  20.0.4           py37hc8dfbb8_1    conda-forge
h5py                      2.10.0          nompi_py37h106b333_102    conda-forge
harfbuzz                  2.4.0                hd8d2a14_3    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
importlib-metadata        1.6.1            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
ipykernel                 5.3.0            py37h43977f1_0    conda-forge
ipython                   7.15.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isl                       0.19                          0    conda-forge
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kiwisolver                1.2.0            py37ha1cc60f_0    conda-forge
krb5                      1.17.1               h1752a42_0    conda-forge
ld64                      450.3                h3c32e8a_4    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hf57f61e_0    conda-forge
libcurl                   7.69.1               hc0b9707_0    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libedit                   3.1.20191231         hed1e85f_0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.2                 h489d428_1    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libssh2                   1.9.0                h39bdce6_2    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
llvmlite                  0.31.0           py37hb548287_1    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
make                      4.3                  h0b31af3_0    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
matplotlib-base           3.2.1            py37hddda452_0    conda-forge
mistune                   0.8.4           py37h9bfed18_1001    conda-forge
mpc                       1.1.0             h4160ff4_1007    conda-forge
mpfr                      4.0.2                h65ac59c_1    conda-forge
natsort                   7.0.1                      py_0    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.1                        py_1    conda-forge
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numba                     0.48.0           py37h4f17bb1_0    conda-forge
numpy                     1.18.5           py37h7687784_0    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.4            py37h94625e5_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               haa940fe_4    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.1.1                     py_1    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
plotly                    4.8.1              pyh9f0ad1d_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            3.0.5                         0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37ha62fc16_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37h9bfed18_0    conda-forge
python                    3.7.6           cpython_h1fd5dd1_6    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-slugify            4.0.0              pyh9f0ad1d_1    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     19.0.1           py37haec44b1_0    conda-forge
qt                        5.12.5               h514805e_3    conda-forge
qtconsole                 4.7.4              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
r-abind                   1.4_5           r36h6115d3f_1003    conda-forge
r-askpass                 1.1               r36h17f1fa6_2    conda-forge
r-assertthat              0.2.1             r36h6115d3f_2    conda-forge
r-backports               1.1.7             r36h17f1fa6_0    conda-forge
r-base                    3.6.3                h0dd4800_2    conda-forge
r-base64enc               0.1_3           r36h17f1fa6_1004    conda-forge
r-bit                     1.1_15.2          r36h17f1fa6_1    conda-forge
r-bit64                   0.9_7           r36h17f1fa6_1002    conda-forge
r-blob                    1.2.1             r36h6115d3f_1    conda-forge
r-boot                    1.3_25            r36h6115d3f_1    conda-forge
r-brew                    1.0_6           r36h6115d3f_1003    conda-forge
r-broom                   0.5.6             r36h6115d3f_1    conda-forge
r-callr                   3.4.3             r36h6115d3f_1    conda-forge
r-car                     3.0_8             r36h6115d3f_0    conda-forge
r-cardata                 3.0_4             r36h6115d3f_0    conda-forge
r-caret                   6.0_86            r36h17f1fa6_2    conda-forge
r-cellranger              1.1.0           r36h6115d3f_1003    conda-forge
r-class                   7.3_17            r36h17f1fa6_1    conda-forge
r-cli                     2.0.2             r36h6115d3f_1    conda-forge
r-clipr                   0.7.0             r36h6115d3f_1    conda-forge
r-cluster                 2.1.0             r36h384270c_3    conda-forge
r-codetools               0.2_16          r36h6115d3f_1002    conda-forge
r-colorspace              1.4_1             r36h17f1fa6_2    conda-forge
r-commonmark              1.7             r36h17f1fa6_1002    conda-forge
r-corrplot                0.84                   r36_1003    conda-forge
r-covr                    3.5.0             r36hc5da6b9_1    conda-forge
r-cowplot                 1.0.0             r36h6115d3f_2    conda-forge
r-crayon                  1.3.4           r36h6115d3f_1003    conda-forge
r-crosstalk               1.1.0.1           r36h6115d3f_1    conda-forge
r-curl                    4.3               r36h17f1fa6_1    conda-forge
r-data.table              1.12.8            r36h17f1fa6_1    conda-forge
r-dbi                     1.1.0             r36h6115d3f_1    conda-forge
r-dbplyr                  1.4.4             r36h6115d3f_0    conda-forge
r-desc                    1.2.0           r36h6115d3f_1003    conda-forge
r-devtools                2.3.0             r36h6115d3f_1    conda-forge
r-digest                  0.6.25            r36hc5da6b9_2    conda-forge
r-distutils               1.0             r36h0b31af3_1003    conda-forge
r-dplyr                   1.0.0             r36hc5da6b9_0    conda-forge
r-dt                      0.13              r36h6115d3f_1    conda-forge
r-ellipsis                0.3.1             r36h17f1fa6_0    conda-forge
r-elpigraph.r             1.0.0           r36h0b31af3_1003    conda-forge
r-essentials              3.6                    r36_2002    conda-forge
r-evaluate                0.14              r36h6115d3f_2    conda-forge
r-fansi                   0.4.1             r36h17f1fa6_1    conda-forge
r-farver                  2.0.3             r36hc5da6b9_1    conda-forge
r-fastmap                 1.0.1             r36hc5da6b9_1    conda-forge
r-forcats                 0.5.0             r36h6115d3f_1    conda-forge
r-foreach                 1.5.0             r36h6115d3f_1    conda-forge
r-foreign                 0.8_76            r36h17f1fa6_1    conda-forge
r-formatr                 1.7               r36h6115d3f_2    conda-forge
r-fs                      1.4.1             r36hc5da6b9_1    conda-forge
r-generics                0.0.2           r36h6115d3f_1003    conda-forge
r-gensa                   1.1.7           r36hd17c0aa_1004    conda-forge
r-ggforce                 0.3.1             r36hc5da6b9_1    conda-forge
r-ggplot2                 3.3.1             r36h6115d3f_0    conda-forge
r-ggpubr                  0.3.0             r36h6115d3f_0    conda-forge
r-ggrepel                 0.8.2             r36hc5da6b9_1    conda-forge
r-ggsci                   2.9             r36h6115d3f_1003    conda-forge
r-ggsignif                0.6.0             r36h6115d3f_1    conda-forge
r-gh                      1.1.0             r36h6115d3f_1    conda-forge
r-gistr                   0.5.0             r36h6115d3f_1    conda-forge
r-git2r                   0.27.1            r36h8d49edc_0    conda-forge
r-glmnet                  4.0               r36h384270c_0    conda-forge
r-glue                    1.4.1             r36h17f1fa6_0    conda-forge
r-gower                   0.2.1             r36h17f1fa6_2    conda-forge
r-gridextra               2.3             r36h6115d3f_1003    conda-forge
r-gtable                  0.3.0             r36h6115d3f_3    conda-forge
r-haven                   2.3.1             r36hee97c7f_0    conda-forge
r-hexbin                  1.28.1            r36h384270c_1    conda-forge
r-highr                   0.8               r36h6115d3f_2    conda-forge
r-hms                     0.5.3             r36h6115d3f_1    conda-forge
r-htmltools               0.4.0             r36hc5da6b9_1    conda-forge
r-htmlwidgets             1.5.1             r36h6115d3f_1    conda-forge
r-httpuv                  1.5.4             r36hc5da6b9_0    conda-forge
r-httr                    1.4.1             r36h6115d3f_2    conda-forge
r-igraph                  1.2.5             r36h28033da_1    conda-forge
r-infotheo                1.2.0           r36h4a8c4bd_1004    conda-forge
r-ini                     0.3.1           r36h6115d3f_1003    conda-forge
r-ipred                   0.9_9             r36h17f1fa6_2    conda-forge
r-irdisplay               0.7                    r36_1002    conda-forge
r-irkernel                1.1               r36h6115d3f_1    conda-forge
r-irlba                   2.3.3             r36h26f5615_3    conda-forge
r-isoband                 0.2.1             r36hc5da6b9_1    conda-forge
r-iterators               1.0.12            r36h6115d3f_1    conda-forge
r-jsonlite                1.6.1             r36h17f1fa6_1    conda-forge
r-kernsmooth              2.23_17           r36h3830744_1    conda-forge
r-knitr                   1.28              r36h6115d3f_1    conda-forge
r-labeling                0.3             r36h6115d3f_1003    conda-forge
r-later                   1.1.0.1           r36hc5da6b9_0    conda-forge
r-lattice                 0.20_41           r36h17f1fa6_2    conda-forge
r-lava                    1.6.7             r36h6115d3f_1    conda-forge
r-lazyeval                0.2.2             r36h17f1fa6_2    conda-forge
r-lifecycle               0.2.0             r36h6115d3f_1    conda-forge
r-lme4                    1.1_23            r36hc5da6b9_1    conda-forge
r-lubridate               1.7.9             r36hc5da6b9_0    conda-forge
r-magrittr                1.5             r36h6115d3f_1003    conda-forge
r-maps                    3.3.0           r36h17f1fa6_1004    conda-forge
r-maptools                1.0_1             r36h17f1fa6_0    conda-forge
r-markdown                1.1               r36h17f1fa6_1    conda-forge
r-mass                    7.3_51.6          r36h17f1fa6_2    conda-forge
r-matrix                  1.2_18            r36h26f5615_3    conda-forge
r-matrixmodels            0.4_1           r36h6115d3f_1003    conda-forge
r-memoise                 1.1.0           r36h6115d3f_1004    conda-forge
r-mgcv                    1.8_31            r36h26f5615_1    conda-forge
r-mime                    0.9               r36h17f1fa6_1    conda-forge
r-minqa                   1.2.4           r36h9db898c_1005    conda-forge
r-modelmetrics            1.2.2.2           r36hc5da6b9_1    conda-forge
r-modelr                  0.1.8             r36h6115d3f_0    conda-forge
r-munsell                 0.5.0           r36h6115d3f_1003    conda-forge
r-nlme                    3.1_148           r36h384270c_0    conda-forge
r-nloptr                  1.2.2.1           r36hc5da6b9_1    conda-forge
r-nnet                    7.3_14            r36h17f1fa6_1    conda-forge
r-numderiv                2016.8_1.1        r36h6115d3f_2    conda-forge
r-openssl                 1.4.1             r36h9d0ceee_1    conda-forge
r-openxlsx                4.1.5             r36hc5da6b9_0    conda-forge
r-pbdzmq                  0.3_3           r36h95f32f2_1003    conda-forge
r-pbkrtest                0.4_7           r36h6115d3f_1003    conda-forge
r-pillar                  1.4.4             r36h6115d3f_0    conda-forge
r-pkgbuild                1.0.8             r36h6115d3f_0    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_1    conda-forge
r-pkgload                 1.1.0             r36hc5da6b9_0    conda-forge
r-plogr                   0.2.0           r36h6115d3f_1003    conda-forge
r-plyr                    1.8.6             r36hc5da6b9_1    conda-forge
r-polyclip                1.10_0            r36hc5da6b9_2    conda-forge
r-polynom                 1.4_0             r36h6115d3f_2    conda-forge
r-praise                  1.0.0           r36h6115d3f_1004    conda-forge
r-prettyunits             1.1.1             r36h6115d3f_1    conda-forge
r-proc                    1.16.2            r36hc5da6b9_1    conda-forge
r-processx                3.4.2             r36h17f1fa6_1    conda-forge
r-prodlim                 2019.11.13        r36hc5da6b9_1    conda-forge
r-progress                1.2.2             r36h6115d3f_2    conda-forge
r-promises                1.1.1             r36hc5da6b9_0    conda-forge
r-pryr                    0.1.4           r36hc5da6b9_1004    conda-forge
r-ps                      1.3.3             r36h17f1fa6_0    conda-forge
r-purrr                   0.3.4             r36h17f1fa6_1    conda-forge
r-quantmod                0.4.17            r36h6115d3f_1    conda-forge
r-quantreg                5.55              r36hb1cbdc7_2    conda-forge
r-r6                      2.4.1             r36h6115d3f_1    conda-forge
r-randomforest            4.6_14          r36h384270c_1003    conda-forge
r-rbokeh                  0.5.1             r36h6115d3f_0    conda-forge
r-rcmdcheck               1.3.3             r36h6115d3f_3    conda-forge
r-rcolorbrewer            1.1_2           r36h6115d3f_1003    conda-forge
r-rcpp                    1.0.4.6           r36hc5da6b9_1    conda-forge
r-rcpparmadillo           0.9.900.1.0       r36hdab79a9_0    conda-forge
r-rcppeigen               0.3.3.7.0         r36hdab79a9_2    conda-forge
r-readr                   1.3.1           r36hc5da6b9_1004    conda-forge
r-readxl                  1.3.1             r36hee97c7f_4    conda-forge
r-recipes                 0.1.12            r36h6115d3f_1    conda-forge
r-recommended             3.6                    r36_1004    conda-forge
r-rematch                 1.0.1           r36h6115d3f_1003    conda-forge
r-rematch2                2.1.2             r36h6115d3f_1    conda-forge
r-remotes                 2.1.1             r36h6115d3f_1    conda-forge
r-repr                    1.1.0             r36h6115d3f_1    conda-forge
r-reprex                  0.3.0             r36h6115d3f_2    conda-forge
r-reshape2                1.4.4             r36hc5da6b9_1    conda-forge
r-rex                     1.2.0             r36h6115d3f_1    conda-forge
r-rio                     0.5.16          r36h6115d3f_1002    conda-forge
r-rlang                   0.4.6             r36h17f1fa6_0    conda-forge
r-rmarkdown               2.2               r36h6115d3f_0    conda-forge
r-roxygen2                7.1.0             r36hc5da6b9_1    conda-forge
r-rpart                   4.1_15            r36h17f1fa6_2    conda-forge
r-rprojroot               1.3_2           r36h6115d3f_1003    conda-forge
r-rsqlite                 2.2.0             r36hc5da6b9_2    conda-forge
r-rstatix                 0.5.0             r36h6115d3f_1    conda-forge
r-rstudioapi              0.11              r36h6115d3f_1    conda-forge
r-rversions               2.0.2             r36h6115d3f_0    conda-forge
r-rvest                   0.3.5             r36h6115d3f_1    conda-forge
r-scales                  1.1.1             r36h6115d3f_0    conda-forge
r-segmented               1.1_0             r36h6115d3f_1    conda-forge
r-selectr                 0.4_2             r36h6115d3f_1    conda-forge
r-sessioninfo             1.1.1           r36h6115d3f_1002    conda-forge
r-shape                   1.4.4                  r36_1003    conda-forge
r-shiny                   1.4.0.2           r36h6115d3f_1    conda-forge
r-sourcetools             0.1.7           r36h4a8c4bd_1002    conda-forge
r-sp                      1.4_2             r36h17f1fa6_0    conda-forge
r-sparsem                 1.78              r36h384270c_1    conda-forge
r-spatial                 7.3_12            r36h17f1fa6_1    conda-forge
r-squarem                 2020.3            r36h6115d3f_0    conda-forge
r-statmod                 1.4.34            r36h1ddc27c_1    conda-forge
r-stringi                 1.4.6             r36h3211bb2_2    conda-forge
r-stringr                 1.4.0             r36h6115d3f_2    conda-forge
r-survival                3.1_12            r36h17f1fa6_1    conda-forge
r-sys                     3.3               r36h17f1fa6_1    conda-forge
r-testthat                2.3.2             r36hc5da6b9_1    conda-forge
r-tibble                  3.0.1             r36h17f1fa6_1    conda-forge
r-tictoc                  1.0             r36h6115d3f_1003    conda-forge
r-tidyr                   1.1.0             r36hc5da6b9_0    conda-forge
r-tidyselect              1.1.0             r36h6115d3f_0    conda-forge
r-tidyverse               1.3.0             r36h6115d3f_2    conda-forge
r-timedate                3043.102        r36h6115d3f_1002    conda-forge
r-tinytex                 0.23              r36h6115d3f_0    conda-forge
r-ttr                     0.23_6            r36h17f1fa6_1    conda-forge
r-tweenr                  1.0.1           r36hc5da6b9_1002    conda-forge
r-usethis                 1.6.1             r36h6115d3f_1    conda-forge
r-utf8                    1.1.4           r36h17f1fa6_1003    conda-forge
r-uuid                    0.1_4             r36h17f1fa6_1    conda-forge
r-vctrs                   0.3.1             r36h17f1fa6_0    conda-forge
r-vgam                    1.1_3             r36h384270c_1    conda-forge
r-viridislite             0.3.0           r36h6115d3f_1003    conda-forge
r-whisker                 0.4               r36h6115d3f_1    conda-forge
r-withr                   2.2.0             r36h6115d3f_1    conda-forge
r-xfun                    0.14              r36h6115d3f_0    conda-forge
r-xml                     3.99_0.3          r36h17f1fa6_1    conda-forge
r-xml2                    1.3.2             r36hc5da6b9_1    conda-forge
r-xopen                   1.0.0           r36h6115d3f_1003    conda-forge
r-xtable                  1.8_4             r36h6115d3f_3    conda-forge
r-xts                     0.12_0            r36h17f1fa6_1    conda-forge
r-yaml                    2.2.1             r36h17f1fa6_1    conda-forge
r-zeallot                 0.1.0           r36h6115d3f_1002    conda-forge
r-zip                     2.0.4             r36h17f1fa6_1    conda-forge
r-zoo                     1.8_8             r36h17f1fa6_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rpy2                      2.9.4           py37r36hfc83f80_3    conda-forge
scikit-learn              0.23.1           py37hf5857e7_0    conda-forge
scipy                     1.4.1            py37hce1b9e5_3    conda-forge
seaborn                   0.10.1                        1    conda-forge
seaborn-base              0.10.1                     py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.1.1           py37hc8dfbb8_0    conda-forge
shapely                   1.7.0            py37hfcf0db4_3    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
statsmodels               0.11.1           py37h9bfed18_1    conda-forge
stream                    1.0                        py_0    bioconda
tapi                      1000.10.8            ha1b3eb9_4    conda-forge
tbb                       2019.9               ha1b3eb9_1    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tktable                   2.10                 h008db23_3    conda-forge
tornado                   6.0.4            py37h9bfed18_1    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
tzlocal                   2.1                pyh9f0ad1d_0    conda-forge
umap-learn                0.4.4            py37hc8dfbb8_0    conda-forge
unidecode                 1.1.1                      py_0    conda-forge
unzip                     6.0                  h0b31af3_1    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zip                       3.0                  h1de35cc_1    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                h4b3e974_3    conda-forge

**Comment by linwang6** [comment] 2020-06-11 18:42
And conda info

$conda info
`     active environment : stream_env
    active env location : /Users/wanglin/miniconda3/envs/stream_env
            shell level : 1
       user config file : /Users/wanglin/.condarc
 populated config files : /Users/wanglin/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __osx=10.12.6
       base environment : /Users/wanglin/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/wanglin/miniconda3/pkgs
                          /Users/wanglin/.conda/pkgs
       envs directories : /Users/wanglin/miniconda3/envs
                          /Users/wanglin/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
`

**Comment by huidongchen** [comment] 2020-06-11 18:50
This seems a notorious rpy2-related issue.. please see this post https://bitbucket.org/rpy2/rpy2/issues/214/segmentation-fault-11-on-mac-os-x-mountain

but someone has revolved it via:
https://stackoverflow.com/questions/39347782/getting-segmentation-fault-core-dumped-error-while-importing-robjects-from-rpy2/53639407#53639407

Let me know if this will work for you.

**Comment by linwang6** [comment] 2020-06-11 19:24
Thanks Huidong, will have a try.

**Comment by linwang6** [comment] 2020-06-11 22:07
Hi, 

Finally it works now. Thanks for your help. 

One last question, this command line "st.plot_dimension_reduction(adata,color=['label'],show_graph=False,show_text=False)" works well, but when I add plotly=True (st.plot_dimension_reduction(adata,color=['label'],show_graph=False,show_text=False,plotly=True)), the figure not pop up, it just prints hundred lines like "{'text/html': '        <script type="text/javascript">\n............", how to show/save this figure? Thanks!

**Comment by huidongchen** [comment] 2020-06-11 22:16
I am glad it is working now! 

Re plotly, the issue is definitely new to me .. but there seem several potential solutions here https://github.com/plotly/plotly_express/issues/114.  

Can you simply try 

`import plotly.io as pio; pio.renderers.default='notebook'`

If it doesn't work, you may also want to try out other solutions.

**Comment by linwang6** [comment] 2020-06-11 22:37
Will try, thanks!

**Comment by huidongchen** [comment] 2020-06-12 13:46
Since the installation issue is resolved, I am closing this issue now. But feel free to open a new issue if the plotly problem still persists.

**Closed by huidongchen** 2020-06-12 13:46 UTC
